@rootApi = http://localhost:5205

GET {{rootApi}}/api/Library/getallbooks
Accept: application/json

###
GET {{rootApi}}/api/Library/getbooksbyauthor/4
Accept: application/json

###
POST {{rootApi}}/api/Library/addbook
Content-type: application/json
{
    "title": "The Power of Positive Thinking",
    "publishedYear": 1999,
    "authorName": "Norman Vincent Peale",
    "authorBio": "An American author and motivational speaker."
}

###
PUT {{rootApi}}/api/Library/updatebook/9
Content-type: application/json
{
    "title": "Not Finished",
    "publishedYear": 2000,
    "authorName": "David Goggins",
    "authorBio": "An American ultramarathon runner, ultra-distance cyclist, and former Navy SEAL."
}

###
DELETE {{rootApi}}/api/Library/deletebook/7

