@rootApi = http://localhost:5205

GET {{rootApi}}/api/Library/getallbooks
Accept: application/json

###
GET {{rootApi}}/api/LibraryManagementService/getallbooks
Accept: application/json

###
GET {{rootApi}}/api/Library/getbooksbyauthor/4
Accept: application/json

###
GET {{rootApi}}/api/LibraryManagementService/getbooksbyauthor/4
Accept: application/json

###
POST {{rootApi}}/api/Library/addbook
Content-type: application/json
{
    "title": "The Power of Positive Thinking",
    "publishedYear": 1999,
    "authorName": "Norman Vincent Peale",
    "authorBio": "An American author and motivational speaker."
}

###
POST {{rootApi}}/api/LibraryManagementService/addbook
Content-type: application/json
{
    "title": "How to win Friends and Influence others",
    "publishedYear": 2000,
    "authorName": "Dale Carnegie",
    "authorBio": "An American author and lecturer."
}

###
PUT {{rootApi}}/api/Library/updatebook/9
Content-type: application/json
{
    "title": "Not Finished",
    "publishedYear": 2000,
    "authorName": "David Goggins",
    "authorBio": "An American ultramarathon runner, ultra-distance cyclist, and former Navy SEAL."
}

###
PUT {{rootApi}}/api/LibraryManagementService/updatebook/4
Content-type: application/json
{
    "title": "Updated Pride and Prejudice",
    "publishedYear": 2005,
    "authorName": "Updated F. Scott Fitzgerald",
    "authorBio": "Updated An American novelist and short story writer."
}

###
DELETE {{rootApi}}/api/Library/deletebook/6

###
DELETE {{rootApi}}/api/LibraryManagementService/deletebook/4

